apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgApWlNtFFGnZqsJo4dhbLSSsIuHy4u0T/u354Mp5+tEQqX+oyUSP0cb1okoZaapw9AV+cjn2tCrlXTOyF7sTHnLioXrD1Hmgleip4+I2lAneZMl5Qik0f/OJVqiCsdwNQnpfJvLmqMqB/V7nPiBoPpPlL6PrI83hHfkwI+tYkljXDCce+TwA2QzQ9DzcI6PEjVXvnl6LrWDOgBvm1xxmlp0e31E9m06o+H9LJEFMnWXtviQEjEXV8AEisQdSpROAK7lxA6D0yI01lMhWIMIPA2S3YYky5Jue69VfZemLoELvX8rrSiNVvzc+rWpZVY1Hs+chXBha5vmcsZgMKbk8ZiMAy/uBrDh39QZlkTKcaOzWXMgILAWOcwTE+EvVh2sdKfgeJv8+l5EfSEdPhWT5crhuTSl/+XLiNIKeczx8iahyEH8vBZLaZ/DW/BjlYmqpZJ4ucZfODkYk5bS8HpV0Q1zWaNJtbdIrgLGY3l24PGSelwNeCAqImledBhtHltMfOWGG8xRN0sNSImXdWfrDqwfy5PZoRx37AisMe6cF0J9/l1rRU2ags25DFjnTyYDiq498tvQJxidFN6jKUULnngCgO2A8OqC5jMs5DCXhst8hyU6/DTmmIWYgafbcMhDNgS7pA9IOHVCJsN8FxDOpU3pscABSiBFAohr9juYmzLYx46EvzehB7Ko6jX7sqAQnItxchOybGzYNA==
    DB_USER: AgC3glsAX2YGQgfp/LmuXGGkXht1mFre3gyyUph5hfymRvWGml7VMexowPKehjCjX8s4/TtOP4vHlC4Bg1vzDr51F88wPDfdDXSqaIWqd6rX47lA62spRJni3WLzFhid37Mb9/EUSXXdeswlNrpbRthnqn9PYQTCYD7ahmEauCzu3mHeUWE/Nr6U48q3korQD/3rmD68Z93LFNArD5y8olct1+ykw1IWIUQ8TEryUBnd4amRJ5Az8PtP4RvuJv0RP/XFEvg/t/0nlhqckh5ZImyvU4brVVRF60ipUpX1RX6b2DP9f+MdRaXorKv8qNxfqrRG+ol+4O6ee/GOK4B/9qHK/JlthjCq0qwWxmAlXhDsSKYChhJhus0Oc0hZZdd7u6fUhUAKDnCkkrChJsPC4Hv6U/RZd3u5NYX0aJ0+qD1/WKBFNmpw6ZxRegSugHeV0pXk0jnyB/O+fVgrO6W3ldM5d6a52rDeUXVAUgU5VAQbCPO/90tKYHNUo9DPQNsYM3/1cgoRkk7LdEqDvXqGlM3rVdL1gGCs0loTGoBIVW60AoZbi1DtgaXkfcn3DLT3k3G1wJVJyCy0PN+FV4z4ccW2jLE5Se1T9rsjnpWSe1x5IzGFWpSCfJwAnYnsY5kJTyUDn4s4yhnUCR14y1uPqgZu3tlQj7qMKVUIvBPJ5jgRY9dGRiJnJ330bgt14bqTZQozEPv798inQw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

